--- #YAML:1.0
name:                TM-View
version:             0.6
abstract:            ~
license:             ~
author:              
    - Alexander Zangerl <alphazulu@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Data::Dumper:                  0
    Test::More:                    0.47
    TM:                            1.43
    XML::Writer:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
